# Generated by Django 5.2.6 on 2025-10-08 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0002_resena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Producto')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=7, verbose_name='Tipo de Movimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('reserva_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.reserva', verbose_name='Reserva Asociada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Vendida')),
                ('precio_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Precio Total')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.producto', verbose_name='Producto Vendido')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
