# Generated by Django 5.2.6 on 2025-09-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo de la imagen', max_length=100)),
                ('imagen', models.ImageField(help_text='Foto para la galería', upload_to='galeria/')),
            ],
        ),
    ]
