# Generated by Django 5.2.6 on 2025-10-09 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_resena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva']},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='reserva',
            name='detalles_privilegios',
            field=models.TextField(blank=True, help_text='Ej: Acceso a piscina, 2 habitaciones, uso de la cocina.', verbose_name='Privilegios Incluidos'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_esperando_pago',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_ingreso',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Ingreso'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='penalizacion_tardia',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=10, verbose_name='Penalización por Hora Extra'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de la Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('esperando_pago', 'Esperando Pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(verbose_name='Fecha del Evento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_personas',
            field=models.PositiveIntegerField(verbose_name='Número de Personas'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_evento',
            field=models.CharField(max_length=100, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
    ]
